name: Test and Lint

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: install node
        run: |
          sudo apt update
          sudo apt install nodejs
          sudo apt install npm
          npm update
  
      - name: install packen-ng and angular
        run: |
          sudo npm install -g ./projects/packen-ng
          sudo npm install -g @angular/common@9
          sudo npm install -g @angular/core@9
          sudo npm install -g @angular/cli@9
          sudo npm install -g @angular-devkit/build-angular
          sudo npm install -g @angular-devkit/build-ng-packagr

      - name: build packen-ng
        run: |
          ng update
          ng build packen-ng --prod

      - name: install packages
        run: npm install
  
      - name: test
        run: npm run test

      - name: lint
        run: npm run lint
